version: '3.8'

services:
    mysql:
        image: mysql:8.0.30
        container_name: mi-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: StudyHub-App
        volumes:
            - mysql_data:/var/lib/mysql

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mi-contenedor-laravel
        ports:
            - "8000:80"
            - "5173:5173" # Map port 5173 of the container to port 5173 of the host
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mi-mysql
            DB_PORT: 3306
            DB_DATABASE: StudyHub-App
            DB_USERNAME: root
            DB_PASSWORD: root
        volumes:
            - ./storage:/var/www/html/storage # Map Laravel storage folder
            - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini # Map PHP configuration file

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: mi-phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: mi-mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1

volumes:
    mysql_data:
